GET http://localhost:1234/pokemon/ditto


### para crear un pokemon, tiene que haber una linea de espacio despues del content-type
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]
}
